# Generated by Django 3.2.16 on 2023-01-10 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RECEIVED', 'received'), ('STARTED', 'started'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('REVOKED', 'revoked'), ('RETRY', 'retried')], default='PENDING', max_length=9)),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('received', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, max_length=200, null=True)),
                ('root_id', models.UUIDField(blank=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('children', models.TextField(blank=True, null=True)),
                ('asn_id', models.UUIDField(blank=True, null=True)),
                ('asn_number', models.IntegerField(blank=True, null=True)),
                ('queue', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'celery_task',
                'verbose_name_plural': 'celery_tasks',
                'db_table': 'celery_tasks',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='CeleryWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('active', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'celery_worker',
                'verbose_name_plural': 'celery_workers',
                'db_table': 'celery_workers',
                'ordering': ['-last_modified'],
            },
        ),
    ]
